version: "3"

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    tty: true

  database:
    image: postgres:15
    volumes:
      - .:/database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  redis:
    image: redis
    volumes:
      - .:/redis
    ports:
      - "6379:6379"
