version: "3"

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db-development
      - db-test

  db-development:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nova_de_novo_development
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nova_de_novo_test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
