default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USER") { "admin" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "admin" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nova_de_novo_development

test:
  <<: *default
  database: nova_de_novo_test

production:
  <<: *default
  database: nova_de_novo_production
  username: nova_de_novo
  password: <%= ENV["NOVA_DE_NOVO_DATABASE_PASSWORD"] %>
